require("@nomicfoundation/hardhat-toolbox");
require("dotenv").config({ path: ".env.local", quiet: true });

// Deployer key for Monad testnet only — a throwaway key generated by
// scripts/generate-deployer.js, never used for anything but deploying this
// contract. Lives in .env.local (gitignored), never committed. See
// scripts/deploy.js for the deployment flow and README notes on funding it
// from https://faucet.monad.xyz.
const DEPLOYER_PRIVATE_KEY = process.env.DEPLOYER_PRIVATE_KEY;

/** @type {import("hardhat/config").HardhatUserConfig} */
module.exports = {
  solidity: {
    version: "0.8.24",
    settings: {
      optimizer: { enabled: true, runs: 200 },
      // OpenZeppelin v5's Bytes.sol uses MCOPY, a Cancun-hardfork opcode —
      // needs evmVersion pinned explicitly or older default targets fail to
      // compile with "Function mcopy not found".
      evmVersion: "cancun",
    },
  },
  networks: {
    monadTestnet: {
      url: process.env.MONAD_TESTNET_RPC_URL || "https://testnet-rpc.monad.xyz/",
      chainId: 10143,
      accounts: DEPLOYER_PRIVATE_KEY ? [DEPLOYER_PRIVATE_KEY] : [],
    },
  },
};
